version: '2'
services:
    formfiller-app:
        image: formfiller
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://formfiller-postgresql:5432/formfiller
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    formfiller-postgresql:
        extends:
            file: postgresql.yml
            service: formfiller-postgresql
